create table animals (id bigint generated by default as identity,
                      name varchar(255) not null,
                      type bigint not null,
                      sex varchar(255) not null,
                      weight bigint not null,
                      cost bigint not null,
                      category varchar(255),
                      primary key (id));


create table files (id bigint generated by default as identity,
                    name varchar(255) not null,
                    size bigint not null,
                    date varchar(255) not null,
                    path varchar(255),
                    primary key (id));